let a=10;
let c=20;
let d=30;

console.log(a);
try{
    console.log(b);
}
catch(err){
    console.log("Getting error : "+err);
}
console.log(c);
console.log(d);

